package com.kibrom.student_id_system.entity;

import jakarta.persistence.*;

import java.time.LocalDateTime;

@Entity
@Table(name = "otps")
public class OTP {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    // OTP code generated by registrar
    @Column(nullable = false, unique = true)
    private String code;


    // Used to know who generated it
    @Column(nullable = false)
    private String createdBy;


    // Student can use OTP only once
    @Column(nullable = false)
    private boolean used = false;


    @Column(nullable = false)
    private LocalDateTime createdAt;


    @Column(nullable = false)
    private LocalDateTime expireAt;



    @PrePersist
    public void prePersist() {
        createdAt = LocalDateTime.now();
    }



    public OTP() {
    }



    public OTP(String code, String createdBy, LocalDateTime expireAt) {

        this.code = code;
        this.createdBy = createdBy;
        this.expireAt = expireAt;

    }



    public Long getId() {
        return id;
    }


    public String getCode() {
        return code;
    }


    public void setCode(String code) {
        this.code = code;
    }


    public String getCreatedBy() {
        return createdBy;
    }


    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }


    public boolean isUsed() {
        return used;
    }


    public void setUsed(boolean used) {
        this.used = used;
    }


    public LocalDateTime getCreatedAt() {
        return createdAt;
    }


    public LocalDateTime getExpireAt() {
        return expireAt;
    }


    public void setExpireAt(LocalDateTime expireAt) {
        this.expireAt = expireAt;
    }
}