package com.kibrom.student_id_system.entity;

import jakarta.persistence.*;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Table(name = "students")
public class Student {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    @Column(nullable = false)
    private String firstName;


    @Column(nullable = false)
    private String middleName;


    @Column(nullable = false)
    private String lastName;


    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ProgramType program;


    @Column(nullable = false)
    private String department;


    @Column(nullable = false)
    private Integer yearLevel;


    @Column(nullable = false)
    private Integer startYear;


    private String photoPath;


    // Generated by system
    @Column(unique = true)
    private String universityEmail;


    private LocalDateTime createdAt;


    @PrePersist
    public void prePersist() {
        createdAt = LocalDateTime.now();
    }


    // Constructors

    public Student() {
    }


    public Student(String firstName,
                   String middleName,
                   String lastName,
                   ProgramType program,
                   String department,
                   Integer yearLevel,
                   Integer startYear,
                   String photoPath) {

        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
        this.program = program;
        this.department = department;
        this.yearLevel = yearLevel;
        this.startYear = startYear;
        this.photoPath = photoPath;
    }


    // Getters and Setters

    public Long getId() {
        return id;
    }


    public String getFirstName() {
        return firstName;
    }


    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }


    public String getMiddleName() {
        return middleName;
    }


    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }


    public String getLastName() {
        return lastName;
    }


    public void setLastName(String lastName) {
        this.lastName = lastName;
    }


    public ProgramType getProgram() {
        return program;
    }


    public void setProgram(ProgramType program) {
        this.program = program;
    }


    public String getDepartment() {
        return department;
    }


    public void setDepartment(String department) {
        this.department = department;
    }


    public Integer getYearLevel() {
        return yearLevel;
    }


    public void setYearLevel(Integer yearLevel) {
        this.yearLevel = yearLevel;
    }


    public Integer getStartYear() {
        return startYear;
    }


    public void setStartYear(Integer startYear) {
        this.startYear = startYear;
    }


    public String getPhotoPath() {
        return photoPath;
    }


    public void setPhotoPath(String photoPath) {
        this.photoPath = photoPath;
    }


    public String getUniversityEmail() {
        return universityEmail;
    }


    public void setUniversityEmail(String universityEmail) {
        this.universityEmail = universityEmail;
    }


    public LocalDateTime getCreatedAt() {
        return createdAt;
    }
}